include_guard(GLOBAL)
# Narrow, idempotent patch against the pinned libdatachannel revision. Fail on upstream drift.
function(wheelplay_replace path before after)
    file(READ "${path}" source)
    string(FIND "${source}" "${after}" applied)
    if(applied EQUAL -1)
        string(FIND "${source}" "${before}" found)
        if(found EQUAL -1)
            message(FATAL_ERROR "libdatachannel media feedback patch mismatch: ${path}")
        endif()
        string(REPLACE "${before}" "${after}" source "${source}")
        file(WRITE "${path}" "${source}")
    endif()
endfunction()
